export enum SharedEventTypes {
    NotifyOfTypeChange = "notify-of-type-change",
    TimeSyncClient = "time-sync-client",
    TimeSyncServer = "time-sync-server",
}

export enum SlaveEventTypes {
    ChangeBackground = "change-background",
    ChangeOrientationColors = "change-orientation-colors",
    DisplayArrowUp = "display-arrow-up",
    DisplayArrowRight = "display-arrow-right",
    SetCounterEvent = "set-counter-event",
    ToggleOrientationColors = "toggle-orientation-colors",
    DisplayImage = "display-image",
    DisplayTriangulationOnSlave = "display-triangulation-on-slave",
    showAnimation = "show-animation",
    NotifyMasterThatPictureCanBeTaken = "notify-master-that-picture-can-be-taken",
    NotifyMasterThatCreeperCanStart = "notify-master-that-creeper-can-start",
    NotifyMasterThatSlaveScreenIsOn = "notify-master-that-slave-screen-is-on",
    NotifyMasterThatSlaveOrientationIsOn = "notify-master-that-slave-orientation-is-on",
    animationFinished = "animation-finished",
    linesShow = "lines-show",
    receiveCutData = "receive-cut-data",
    receiveTriangulationData = "receive-triangulation-data",
    Reset = "reset",
    StartVideo = "start-video",
    StopVideo = "stop-video",
    PauseVideo = "pause-video",
    startAnimation = "start-animation-on-slave",
    stopAnimation = "stop-animation-on-slave",
    sendVideoTimeStamp = "return-time-stamp-of-video",
    GetVideoTimeStamp = "retrieve-time-stamp-of-video",
    HandleVideoTimeStamp = "handle-video-time-stamps-from-slaves",
    UpdateVideoTime = "update-video-time-stamp",

    DisplayDetectionColor = "display-detection-color",
    DisplayedDetectionColor = "displayed-detection-color",
    DisplayOrientationColors = "display-orientation-colors",
    DisplayedOrientationColors = "displayed-orientation-colors",
    DisplayTrackingScreen = "display-tracking-screen",
    DisplayedTrackingScreen = "displayed-tracking-screen",
}

export enum MasterEventTypes {
    ChangeSlaveBackgrounds = "change-slave-backgrounds",
    ChangeSlaveBackground = "change-slave-background",
    ToggleSlaveOrientationColors = "toggle-slave-orientation-colors",
    SlaveChanges = "notify-master-of-slaves",
    SendArrowsUp = "send-arrows-up",
    SendArrowsRight = "send-arrows-right",
    NotifySlavesOfStartTimeCounter = "notify-slaves-of-start-time-counter",
    DisplayImageOnSlave = "display-image-on-slave",
    SendTriangulationOnSlave = "send-triangulation-on-slave",
    GiveUpMaster = "give-up-master",
    ShowAnimationOnSlave = "show-animation-on-slave",
    HandleNextSlaveFlowHanlderStep = "handle-next-slave-flow-handler-step",
    nextLine = "next-line",
    triangulationShow = "triangulation-show",
    sendCutData = "send-cut-data",
    sendTriangulationData = "send-triangulation-data",
    ResetSlave = "reset-slave",
    startAnimation = "start-animation",
    stopAnimation = "stop-animation",
    StartVideoOnSlaves = "start-video-on-slaves",
    StopVideoOnSlaves = "stop-video-on-slaves",
    PauseVideoOnSlaves = "pause-video-on-slaves",
    GetVideoTimeStampsOnSlaves = "retrieve-time-stamp-of-video",
    HandleVideoTimeStampsOnSlaves = "handle-video-time-stamps-from-slaves",
    UpdateVideoTimeOnSlave = "update-video-time-stamps-on-slave",

    RequestDetectionColor = "request-detection-color",
    ConfirmedDetectionColor = "confirmed-detection-color",
    RequestOrientationColors = "request-orientation-colors",
    ConfirmedOrientationColors = "confirmed-orientation-colors",
    RequestTrackingScreen = "request-tracking-screen",
    ConfirmedTrackingScreen = "confirmed-tracking-screen",
}
